package main

// Sum executes the core logic of this function.
//
// Parameters:
//   - a (int):
//   - b (int):
//
// Returns:
//   - int:
//
// Generated by go-doc-agent.
func Sum(a int, b int) int {
	return a + b
}
