package io

import (
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/amonvix/go-doc-agent/internal/context"
	"github.com/amonvix/go-doc-agent/internal/generator"
)

func WriteCommentsMarkdown(
	projectPath context.Path,
	comments []generator.CommentDoc,
) error {
	log.Println("[writer] writing outputs")

	if len(comments) == 0 {
		return nil
	}

	docsDir := filepath.Join(projectPath.String(), "docs")
	if err := os.MkdirAll(docsDir, 0o755); err != nil {
		return err
	}

	outPath := filepath.Join(docsDir, "comments.generated.md")

	byFile := map[string][]generator.CommentDoc{}
	for _, c := range comments {
		byFile[c.FilePath] = append(byFile[c.FilePath], c)
	}

	files := make([]string, 0, len(byFile))
	for f := range byFile {
		files = append(files, f)
	}
	sort.Strings(files)

	var b strings.Builder

	b.WriteString("# Generated Function Documentation\n\n")
	b.WriteString("Automatically generated by **go-doc-agent**.\n\n")

	for _, file := range files {

		b.WriteString("## ")
		b.WriteString(file)
		b.WriteString("\n\n")

		funcs := byFile[file]
		sort.Slice(funcs, func(i, j int) bool {
			return funcs[i].Target < funcs[j].Target
		})

		for _, fn := range funcs {
			b.WriteString("### ")
			b.WriteString(fn.Target)
			b.WriteString("\n\n")
			b.WriteString(fn.Text)
			b.WriteString("\n\n")
		}
	}

	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}
